const AVAILABLE_ACTIONS = {
  ENCODE: 'encode',
  DECODE: 'decode',
};

const NUMBER_OF_LETTERS = 26;

const ENGLISH_ALPHABET_ASCII_RANGES = {
  UPPER_CASE_LOWER_BOUND: 65,
  UPPER_CASE_UPPER_BOUND: 90,
  LOWER_CASE_LOWER_BOUND: 97,
  LOWER_CASE_UPPER_BOUND: 122,
};

module.exports = {
  NUMBER_OF_LETTERS,
  AVAILABLE_ACTIONS,
  ENGLISH_ALPHABET_ASCII_RANGES,
};
